### ISSUE TITLE
Compute HHA feature

### ISSUE THREAD

**Issue by fangyan93** [SSAW14/STD2P#1]
Hello, @SSAW14, I am interested in object detection for RGBD image and want to use HHA feature representation of depth image, noticed you have used it in this project, are you using Matlab coding from s-gupta rcnn-depth repo? Or do you have implementation in Python? Thanks

**Comment by SSAW14** [comment]
Hi Fangyan,

I used Gupta's matlab code.
Please check here: https://github.com/s-gupta/rcnn-depth.

Best,
Yang

**Comment by fangyan93** [comment]
@SSAW14 Thank you so much for reply. More one question please, in this case, if test in real time, doest every depth image needs to be preprocessed by the matlab code first? If yes, how to achieve real time test ?

**Comment by SSAW14** [comment]
Hi,

First of all, my work cannot run in real-time. In the experiment of our
paper, I need to compute information from multiple frame, so it needs some
time.
In practice, we can save the posterior of previous frame to save
computation time.

In my work, I do posterior level fusion, so I think it is possible to use
RGB only in some frames, because it also provide posterior.
About the HHA representation implementation, it will speed up the
computation if you re-implement it without matlab. The release code is only
used for research, and running speed is not the story of this work.

Yang

**Comment by fangyan93** [comment]
@SSAW14 Got it! Thank you very much! By the way, excellent work! 😁
